### ISSUE TITLE
Edit finger joint

### ISSUE THREAD

**Issue by gavspav** [FlorianPommerening/FingerJoints#12] opened 2022-01-11 23:17 UTC
Am I correct in thinking it is not currently possible to easily edit ones finger joints using this tool - at least not using edit feature?

And not possible to use variables - or if you do the joints will not update if the variables change?

Thanks.

**Comment by FlorianPommerening** [comment] 2022-01-12 00:31
Yes, unfortunately the Fusion API doesn't support this right now. There is an API feature called "Custom Features" that makes the required API changes but it is still in preview mode and they don't recommend publishing add-ins based on it, because it might still change. Issue #3 is about implementing custom features (although the name of the issue is misleading, I'll change it). I'll close this issue as a duplicate and we can continue the discussion in #3.

**Closed by FlorianPommerening** 2022-01-12 00:31 UTC
